# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_landpurchasepayment_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landtransferfee',
            name='land_size',
        ),
    ]
