# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0021_land_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuserprofile',
            name='id_no',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name=b'National ID Number'),
        ),
    ]
