# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0022_auto_20170118_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
