# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0024_auto_20170118_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuserprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'land/images/profile/'),
        ),
    ]
