# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0026_land_title_deed_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpurchases',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
